### ISSUE TITLE
error occur on dataloader when train 

### ISSUE THREAD

**Issue by ThreeSevenGO** [WenlongZhang0724/RankSRGAN#3]
Thank you for your work!
I try to train the RankSRGAN model, but I don't have Matlab on my computer, so I turned off the code about matlab. I don't know if because of it I got the error as followed.
I checked the path of the data, and there was no error.
Have you ever been in this situation?

```
19-08-30 14:29:21.129 - INFO: Model [SRGANModel] is created.
19-08-30 14:29:21.129 - INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "train_without_matlab.py", line 199, in <module>
    main()
  File "train_without_matlab.py", line 110, in main
    for _, train_data in enumerate(train_loader):
  File "d:\Anaconda3\envs\pytorch110\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "d:\Anaconda3\envs\pytorch110\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "d:\Anaconda3\envs\pytorch110\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "d:\Anaconda3\envs\pytorch110\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "d:\Anaconda3\envs\pytorch110\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "d:\Anaconda3\envs\pytorch110\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "d:\Anaconda3\envs\pytorch110\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle Environment objects

(pytorch110) E:\heqinwen\RankSRGAN\codes>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\Anaconda3\envs\pytorch110\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "d:\Anaconda3\envs\pytorch110\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by WenlongZhang0724** [comment]
I have updated the training file, [train.py](https://github.com/WenlongZhang0724/RankSRGAN/blob/master/codes/train.py) for validation with PSNR , [train_niqe.py](https://github.com/WenlongZhang0724/RankSRGAN/blob/master/codes/train_niqe.py) for validation with PSNR and NIQE. Please test the train.py on your computer.

Best wishes

**Comment by ThreeSevenGO** [comment]
This error still exists on my Windows computer. I run the same code on my Linux computer, and it works.
Thank you for the solution you provided.
